[package]
name = "oxide"
version = "0.3.2"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
peg = "0.8.0"
strum = { version = "0.24", features = ["derive"] }
unicode-xid = "0.2.2"

[features]
trace = ["peg/trace"]
